import logo from "./logo.svg";
import nav1 from "./nav1.svg";
import nav2 from "./nav2.svg";
import nav3 from "./nav3.svg";
import nav4 from "./nav4.svg";
import nav5 from "./nav5.svg";
import arrowDown from "./arrow-down.svg";
import prevBtn from "./prev-btn.svg";
import nextBtn from "./next-btn.svg";
import closeBtn from "./close-btn.svg";
import drawIcon from "./draw.svg";
import uploadIcon from "./close-btn.svg";
export const img = {logo,nav1,nav2,nav3,nav4,nav5,arrowDown,prevBtn,nextBtn,closeBtn,drawIcon,uploadIcon};